export default function () {
  return {
    groups: localStorage.getItem('groups') || [],
    credit: localStorage.getItem('credit') || 0,
    role: localStorage.getItem('role') || -1,
    username: localStorage.getItem('username') || 'unknown',
    user_permissions: localStorage.getItem('user_permissions') || [],
    key: localStorage.getItem('key') || '',
    isLoading: false,
    gameType: {
      SL: 'SLOT',
      LC: 'LIVE-CASINO',
      SB: 'SPORTBOOK',
      OT: 'OTHERS',
      ES: 'ESPORT',
      LK: 'LOTTO',
      PK: 'POKER',
      FH: 'FISHING',
      CB: 'CARD & BOARD',
      MG: 'MINI GAME',
    },

    bank: [
      {
        value: null,
        code: null,
        text: 'กรุณาเลือกธนาคาร',
      },
      {
        value: 'KBZpay',
        code: 'KBZpay',
        text: 'KBZpay',
      },

      {
        value: 'WAVEPAY',
        code: 'WAVEPAY',
        text: 'WAVEPAY',
      },
      {
        value: 'KBANK',
        code: 'KBANK',
        text: 'KBANK',
      },
      {
        value: 'TRUEWALLET',
        code: 'TRUEWALLET',
        text: 'ทรูวอลเล็ต',
      },
      {
        value: 'TMB',
        code: 'TMB',
        text: 'TTB',
      },
      {
        value: 'BBL',
        code: 'BBL',
        text: 'ธนาคารกรุงเทพ',
      },
      {
        value: 'KTB',
        code: 'KTB',
        text: 'ธนาคารกรุงไทย',
      },
      {
        value: 'BAY',
        code: 'BAY',
        text: 'ธนาคารกรุงศรีอยุธยา',
      },
      {
        value: 'KKP',
        code: 'KKP',
        text: 'ธนาคารเกียรตินาคินภัทร',
      },
      {
        value: 'CIMB',
        code: 'CIMB',
        text: 'ธนาคารซีไอเอ็มบีไทย',
      },
      {
        value: 'TISCO',
        code: 'TISCO',
        text: 'ธนาคารทิสโก้',
      },
      {
        value: 'TBANK',
        code: 'TBANK',
        text: 'ธนาคารธนชาต',
      },
      {
        value: 'UOBT',
        code: 'UOBT',
        text: 'ธนาคารยูโอบี',
      },
      {
        value: 'TCD',
        code: 'TCD',
        text: 'ธนาคารไทยเครดิตเพื่อรายย่อย',
      },
      {
        value: 'LHFG',
        code: 'LHFG',
        text: 'ธนาคารแลนด์แอนด์ เฮ้าส์',
      },
      {
        value: 'BAAC',
        code: 'BAAC',
        text: 'ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร',
      },
      {
        value: 'GSB',
        code: 'GSB',
        text: 'ธนาคารออมสิน',
      },
      {
        value: 'GHB',
        code: 'GHB',
        text: 'ธนาคารอาคารสงเคราะห์',
      },
      {
        value: 'ISBT',
        code: 'ISBT',
        text: 'ธนาคารอิสลามแห่งประเทศไทย',
      },
      {
        value: 'SCB',
        code: 'SCB',
        text: 'ธนาคารไทยพานิชย์',
      },
    ],
    provider: {
      SML: 'Smart Lotto',
      S2S: 'Sexy Baccarat',
      EVP: 'EVOPLAY',
      JKR: 'Joker',
      RRG: 'Red Rake Gaming SLOT',
      RTG: 'Red Tiger',
      HBO: 'HABANERO',
      BGO: 'Booongo',
      AVX: 'AvatarUX',
      GNJ: 'Green Jade',
      GMX: 'Gamzix',
      GHO: 'Golden Hero',
      CLT: 'Caleta Gaming',
      YLT: 'Yolted',
      KLB: 'Kalamba Games',
      MST: 'MrSlotty',
      SBE: 'Spribe',
      TBG: 'Turbogames',
      TMH: 'Tom Horn',
      TGE: 'Tangente',
      WZN: 'Wazdan',
      RVG: 'Revolver Gaming',
      PSN: 'Playson',
      MNC: 'Mancala Gaming',
      MGE: 'Red Rake Gaming',
      HSG: 'Hacksaw Gaming',
      SPG: 'SPADE GAMING',
      NTN: 'NetEnt',
      PNG: "Play'n Go",
      ONT: 'OneTouch',
      BST: 'BETSOFT',
      YGG: 'Yggdrasil',
      BPT: 'Blueprint Gaming',
      NLC: 'Nolimit City',
      PGP: 'PRAGMATIC PLAY',
      PPL: 'Pragmatic Play Live',
      EZG: 'Ezugi',
      BGT: 'BetGames.TV',
      EBT: 'eBET',
      OTL: 'Onetouch Live',
      EVO: 'EVOLUTION',
      ASG: 'ASIAGAMING',
      SSC: 'Super Spade Games',
      CQ9: 'CQ9',
      AMX: 'AMEBA',
      PGA: 'PG Soft',
      GMT: 'Gamatron',
      JLS: 'JILI',
      DGS: 'Dream Gamings',
      AP: 'AMB Poker',
      UF: 'UFA Sportbook',
      WC: 'WM Casino',
      AT: 'Allbet',
      AV: 'AVIA Gaming',
      CY: 'CitiBet',
      SO: 'SBO',
      WB: 'Wbet',
      SA: 'SA Gaming',
    },
  }
}
