export default function () {
  return {
    credit: localStorage.getItem('credit') || 0,
    role: localStorage.getItem('role') || -1,
    username: localStorage.getItem('username') || 'unknown',
    user_permissions: localStorage.getItem('user_permissions') || [],
    key: localStorage.getItem('key') || '',
    isLoading: false,
    gameType: {
      SL: 'SLOT',
      LC: 'LIVE-CASINO',
      SB: 'SPORTBOOK',
      OT: 'OTHERS',
      ES: 'ESPORT',
      LK: 'LOTTO',
      PK: 'POKER',
      FH: 'FISHING',
      CB: 'CARD & BOARD',
      MG: 'MINI GAME',
    },
    provider: {
      AB: 'Allbet',
      AG: 'ASIA GAMING',
      CQ: 'CQ9',

      AV: 'AVIA Gaming',
      CB: 'CitiBet',
      DG: 'Dream Gaming',
      FG: 'Fun Gaming',
      FI: 'Maverick',
      F5: 'Maverick',
      GE: 'Evolution Gaming',
      GM: 'Gamatron',
      GT: 'BTI',
      L4: 'LIVE22',
      PG: 'PG Soft',
      PR: 'Pragmatic Play',
      PX: 'Playtech',
      S2: 'Sexy Baccarat',
      SG: 'Spade Gaming',
      SO: 'SBO',
      SY: 'Simple Play',
      VV: 'Vivo Gaming',
      WB: 'Wbet',

      AM: 'Ameba',
      CQ: 'CQ9',
      EP: 'Evoplay',
      JK: 'Joker',
      SA: 'SA Gaming',
      RE: 'Red Tiger',
    },
    bank: [
      {
        value: null,
        code: null,
        text: 'กรุณาเลือกธนาคาร',
      },
      {
        value: 'KBZpay',
        code: 'KBZpay',
        text: 'KBZpay',
      },

      {
        value: 'WAVEPAY',
        code: 'WAVEPAY',
        text: 'WAVEPAY',
      },
      {
        value: 'KBANK',
        code: 'KBANK',
        text: 'KBANK',
      },
      {
        value: 'TRUEWALLET',
        code: 'TRUEWALLET',
        text: 'ทรูวอลเล็ต',
      },
      {
        value: 'TMB',
        code: 'TMB',
        text: 'TTB',
      },
      {
        value: 'BBL',
        code: 'BBL',
        text: 'ธนาคารกรุงเทพ',
      },
      {
        value: 'KTB',
        code: 'KTB',
        text: 'ธนาคารกรุงไทย',
      },
      {
        value: 'BAY',
        code: 'BAY',
        text: 'ธนาคารกรุงศรีอยุธยา',
      },
      {
        value: 'KKP',
        code: 'KKP',
        text: 'ธนาคารเกียรตินาคินภัทร',
      },
      {
        value: 'CIMB',
        code: 'CIMB',
        text: 'ธนาคารซีไอเอ็มบีไทย',
      },
      {
        value: 'TISCO',
        code: 'TISCO',
        text: 'ธนาคารทิสโก้',
      },
      {
        value: 'TBANK',
        code: 'TBANK',
        text: 'ธนาคารธนชาต',
      },
      {
        value: 'UOBT',
        code: 'UOBT',
        text: 'ธนาคารยูโอบี',
      },
      {
        value: 'TCD',
        code: 'TCD',
        text: 'ธนาคารไทยเครดิตเพื่อรายย่อย',
      },
      {
        value: 'LHFG',
        code: 'LHFG',
        text: 'ธนาคารแลนด์แอนด์ เฮ้าส์',
      },
      {
        value: 'BAAC',
        code: 'BAAC',
        text: 'ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร',
      },
      {
        value: 'GSB',
        code: 'GSB',
        text: 'ธนาคารออมสิน',
      },
      {
        value: 'GHB',
        code: 'GHB',
        text: 'ธนาคารอาคารสงเคราะห์',
      },
      {
        value: 'ISBT',
        code: 'ISBT',
        text: 'ธนาคารอิสลามแห่งประเทศไทย',
      },
      {
        value: 'SCB',
        code: 'SCB',
        text: 'ธนาคารไทยพานิชย์',
      },
    ],
  }
}
